from elasticsearch import Elasticsearch
from datetime import datetime

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "Welcome#1"
g_data_json = {'Memory size(GB)': '2.42 GiB', 'Session num(ea)': 5, 'Lock num(ea)': 0, 'Transaction(ea)': 1, 'Tmp size(MB)': '0.09', 'Table Full scan(ea)': 14, 'Database size(GB)': '8.40', 'ErrorLog(1hour,ea)': 1, 'Slow query(>1s,ea)': 0, 'GroupHA(ea)': 0, 'Replication(ea)': '0'}

# Create the client instance
client = Elasticsearch(
    "https://localhost:9200",
#    ca_certs="/etc/elasticsearch/certs/http_ca.crt",
    verify_certs=False,
    ssl_show_warn=False,
    basic_auth=("admin", ELASTIC_PASSWORD)
)

# Successful response!
print(client.info())
g_data_json.update({'timestamp': datetime.now()})

if not client.indices.exists(index="mysql-mon") :
    client.indices.create(index="mysql-mon")
client.index(index="mysql-mon", document=g_data_json)
